# Pandas method (Data Cleaning)

In [4]:
import pandas as pd

df=pd.read_csv("C:\\Users\\ywako\\Downloads\\customer_analytics - customer_analytics.csv")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

#### Part 1 — Inspect & Understand the Dataset
#### Q1. Load the dataset
#### Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
#### Then display the first 10 rows.
#### Use: pd.read_csv(), head()

In [5]:
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

#### Q2. Inspect the end of the dataset
#### Display the last 15 rows.
#### Use: tail()

In [6]:
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

#### Q3. Random inspection
#### Display 10 random records.
#### Use: sample()

In [7]:
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1683,100152,52,NaN,NaN,548,2,Hyderabad,Premium,Mobile,2021-10-13 00:00:00,Yes,High,20855.75,40,3.1
54,101365,27,172159,201009.76,831,4,Bangalore,Corporate,Mobile,2023-06-12 00:00:00,No,Low,37462.72,84,9.9
1681,101144,34,166214,260523.24,324,10,Hyderabad,Premium,Branch,2022-12-06 00:00:00,No,High,3220.2,6,6.9
1776,101785,54,NaN,5515.84,693,2,Delhi,SME,Agent,2024-07-31 00:00:00,Yes,High,38534.07,123,4.0
1731,101350,44,144654,231754.89,472,8,kolkata,SME,Agent,2025-08-10 00:00:00,NaN,High,9741.6,81,4.5
1049,100843,58,NaN,76007.15,629,5,Mumbai,Premium,Online,NaN,Yes,Medium,5762.14,129,4.4
1945,101846,35,59518,38210.84,661,11,Pune,Retail,Branch,2023-06-28 00:00:00,NaN,Medium,28353.75,126,5.2
531,101394,60,200006,109765.74,462,4,Bangalore,Retail,Branch,2022-10-25 00:00:00,Yes,High,32375.14,119,8.2
138,101527,66,176716,238178.82,357,10,Delhi,Retail,Mobile,2025-06-11 00:00:00,Yes,High,28654.07,146,6.4
352,100355,52,148629,142790.32,482,9,Mumbai,Premium,Branch,2023-07-08 00:00:00,Yes,High,22832.62,64,3.1

#### Q4. Dataset audit
#### Use info() to identify:
#### • Number of rows
#### • Number of columns
#### • Columns with missing values
#### • Columns having incorrect/object datatypes
#### Use: info()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

#### Q5. Missing-value audit
#### Calculate the number of missing values in every column.
#### Then verify the result using both:
#### isnull() and isna()

In [9]:
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

#### Part 2 — Detect & Fix Data Quality Problems
#### Q6. Duplicate investigation
#### Find how many duplicate rows exist.
#### Do not remove them yet.
#### Use: duplicated()

In [10]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2040, dtype: bool

#### Q7. Remove duplicates
#### Remove all duplicate records and store the cleaned result back into df.
#### Then verify that duplicates no longer exist.
#### Use: drop_duplicates(), duplicated()

In [11]:
df.duplicated().sum()

np.int64(40)

#### Q8. Numeric column investigation
#### Select only numeric columns.
#### Identify which columns are currently numeric and which potentially numeric columns have
#### become object because of invalid values.
#### Use: select_dtypes()####

In [12]:
df.dtypes

Customer_ID             int64
Age                    object
Annual_Income          object
Account_Balance        object
Credit_Score           object
Tenure_Years            int64
City                   object
Segment                object
Channel                object
Join_Date              object
Active                 object
Risk_Level             object
Monthly_Spend          object
Transactions           object
Satisfaction_Score    float64
dtype: object

#### Q9. Fix Age
#### The Age column contains:
#### • Valid numbers
#### • Missing values
#### • Invalid text such as unknown, N/A, etc.
#### Convert Age into a proper numeric column.
#### Invalid values should become missing values.
#### Then fill missing Age values using the median age.
#### Use: pd.to_numeric(), median(), fillna()

In [13]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

median_age = df["Age"].median()

df["Age"] = df["Age"].fillna(median_age)
df["Age"].isnull().sum()

np.int64(0)

#### Q10. Fix Annual Income
#### Clean Annual_Income.
#### Requirements:
#### 1. Convert invalid values to missing.
#### 2. Convert the column to a numeric datatype.
#### 3. Calculate the median.
#### 4. Fill missing values using the median.
#### Use: pd.to_numeric(), median(), fillna(), astype()

In [19]:
import pandas as pd

In [24]:
df["Annual_Income"] = pd.to_numeric(df["Annual_Income"],errors="coerce")
df["Annual_Income"] = df["Annual_Income"].astype(float)

median_income = df["Annual_Income"].median()
print("Median Annual Income:", median_income)
df["Annual_Income"] = df["Annual_Income"].fillna(median_income)

df["Annual_Income"].isnull().sum()
df["Annual_Income"].dtype

Median Annual Income: 139999.5

dtype('float64')

#### Part 3 — Numerical Cleaning
#### Q11. Clean Account Balance
#### The Account_Balance column contains invalid strings and missing values.
#### Clean the column and replace missing values with the mean Account Balance.
#### Use:• pd.to_numeric()
#### • mean()
#### • fillna()

In [25]:
df["Account_Balance"] = pd.to_numeric(df["Account_Balance"],errors="coerce")

mean_balance = df["Account_Balance"].mean()
print("Mean Account Balance:", mean_balance)

df["Account_Balance"] = df["Account_Balance"].fillna(mean_balance)

print("Missing values:", df["Account_Balance"].isnull().sum())
print("Data type:", df["Account_Balance"].dtype)

Mean Account Balance: 151049.05422603106
Missing values: 0
Data type: float64

#### Q12. Clean Credit Score
#### Clean Credit_Score.
#### Invalid values should become missing.
#### Then replace missing values with the median Credit Score.
#### Finally convert the column to integer.
#### Use:
#### • pd.to_numeric()
#### • median()
#### • fillna()
#### • astype()

In [26]:
df["Credit_Score"] = pd.to_numeric(df["Credit_Score"],errors="coerce")

median_score = df["Credit_Score"].median()
print("Median Credit Score:", median_score)

df["Credit_Score"] = df["Credit_Score"].fillna(median_score)
df["Credit_Score"] = df["Credit_Score"].astype(int)

print(df["Credit_Score"].isnull().sum())
print(df["Credit_Score"].dtype)

Median Credit Score: 570.0
0
int64

#### Q13. Clean Monthly Spend
#### Clean Monthly_Spend.
#### Then:
#### • Convert it to numeric.
#### • Replace invalid values.
#### • Replace missing values using the median.
#### • Make sure the final column is numeric.

In [27]:
df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"],errors="coerce")

median_spend = df["Monthly_Spend"].median()
print("Median Monthly Spend:", median_spend)

df["Monthly_Spend"] = df["Monthly_Spend"].fillna(median_spend)

print("Missing values:", df["Monthly_Spend"].isnull().sum())
print("Data type:", df["Monthly_Spend"].dtype)

Median Monthly Spend: 24646.77
Missing values: 0
Data type: float64

#### Q14. Clean Transactions
#### The Transactions column contains invalid strings.
#### Convert it to numeric and replace invalid values with the median number of transactions.
#### Then convert the final column to integer.

In [28]:
df["Transactions"] = pd.to_numeric(df["Transactions"],errors="coerce")

median_transactions = df["Transactions"].median()
print("Median Transactions:", median_transactions)

df["Transactions"] = df["Transactions"].fillna(median_transactions)
df["Transactions"] = df["Transactions"].astype(int)

print("Missing values:", df["Transactions"].isnull().sum())
print("Data type:", df["Transactions"].dtype)

Median Transactions: 76.0
Missing values: 0
Data type: int64

#### Q15. Clean Satisfaction Score
#### Clean Satisfaction_Score.
#### Replace missing/invalid values using the mean Satisfaction Score.
#### Then convert the column to float.

In [29]:
df["Satisfaction_Score"] = pd.to_numeric(df["Satisfaction_Score"],errors="coerce")

mean_score = df["Satisfaction_Score"].mean()
print("Mean Satisfaction Score:", mean_score)

df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(mean_score)

df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)

print("Missing values:", df["Satisfaction_Score"].isnull().sum())
print("Data type:", df["Satisfaction_Score"].dtype)

Mean Satisfaction Score: 5.595907928388747
Missing values: 0
Data type: float64

#### Part 4 — Date Cleaning
#### Q16. Investigate Join_Date
#### Inspect the Join_Date column.
#### Identify the problems caused by:
#### • Missing dates
#### • Different date formats
#### • Invalid date strings
#### Do not clean it yet.

In [30]:
print("Join_Date column:")
print(df["Join_Date"])

print("\nMissing dates:")
print(df["Join_Date"].isnull().sum())

print("\nData type:")
print(df["Join_Date"].dtype)

print("\nUnique date values:")
print(df["Join_Date"].dropna().unique())

Join_Date column:
0       2022-08-15 00:00:00
1       2025-01-11 00:00:00
2       2024-08-01 00:00:00
3       2021-05-15 00:00:00
4       2026-02-03 00:00:00
               ...
2035    2021-07-10 00:00:00
2036    2025-07-05 00:00:00
2037    2022-10-17 00:00:00
2038    2023-08-26 00:00:00
2039                    NaN
Name: Join_Date, Length: 2040, dtype: object

Missing dates:
102

Data type:
object

Unique date values:
['2022-08-15 00:00:00' '2025-01-11 00:00:00' '2024-08-01 00:00:00' ...
 '2025-09-10 00:00:00' '2022-10-17 00:00:00' '2023-08-26 00:00:00']

#### Q17. Convert Join_Date
#### Convert Join_Date into a proper Pandas datetime column.
#### Any invalid dates should become missing values.
#### Use: pd.to_datetime()

In [35]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors="coerce")
print(df["Join_Date"].head())

print("\nData type:")
print(df["Join_Date"].dtype)

print("\nMissing/invalid dates:")
print(df["Join_Date"].isnull().sum())

0   2022-08-15
1   2025-01-11
2   2024-08-01
3   2021-05-15
4   2026-02-03
Name: Join_Date, dtype: datetime64[ns]

Data type:
datetime64[ns]

Missing/invalid dates:
128

#### Q18. Handle missing dates
#### After conversion, find how many missing dates remain.
#### Then replace missing dates appropriately using a reasonable date-based strategy.

In [37]:
print("Missing dates before filling:",df["Join_Date"].isnull().sum())

median_date = df["Join_Date"].dropna().median()
print("Median Join Date:", median_date)

df["Join_Date"] = df["Join_Date"].fillna(median_date)

print("Missing dates after filling:",df["Join_Date"].isnull().sum())

Missing dates before filling: 0
Median Join Date: 2023-08-26 12:00:00
Missing dates after filling: 0

#### Part 5 — Categorical Cleaning
#### Q19. Clean City
#### The City column contains values such as:
#### Mumbai
#### mumbai
#### Mumbai
#### mumbai
#### Standardize the values so that logically identical cities are represented consistently.
#### Then check the unique frequency distribution.
#### Use: replace(), value_counts()

In [38]:
df["City"] = df["City"].replace({
    "mumbai": "Mumbai",
    "MUMBAI": "Mumbai",
    "delhi": "Delhi",
    "DELHI": "Delhi",
    "pune": "Pune",
    "PUNE": "Pune"
})

print(df["City"].value_counts())

City
Mumbai       314
Delhi        288
Hyderabad    278
Pune         274
Kolkata      262
Chennai      242
Bangalore    236
hyderabad     20
bangalore     18
kolkata       14
chennai       13
Name: count, dtype: int64

#### Q20. Analyze Segment
#### Check the frequency of:
#### Retail
#### SME
#### Corporate
#### Premium
#### Also determine whether missing values exist.
#### Then replace missing Segment values with the most appropriate category based on your analysis.
#### Use: value_counts(), fillna()

In [39]:
print("Segment frequency:")
print(df["Segment"].value_counts(dropna=False))

print("\nMissing values:",df["Segment"].isnull().sum())

most_common_segment = df["Segment"].value_counts().idxmax()
print("Most common Segment:", most_common_segment)

df["Segment"] = df["Segment"].fillna(most_common_segment)
print("\nMissing values after filling:",
      df["Segment"].isnull().sum())

Segment frequency:
Segment
Premium      523
Retail       481
Corporate    475
SME          456
NaN          105
Name: count, dtype: int64

Missing values: 105
Most common Segment: Premium

Missing values after filling: 0

#### Q21. Clean Active
#### Active is supposed to be a binary column, but it contains:
#### Yes
#### No
#### Y
#### N
#### YES
#### NO
#### yes
#### no
#### 1
#### 0
#### Transform these into a consistent representation:
#### Yes
#### No
#### Then verify the result with value_counts().
#### Use: replace(), value_counts()

In [40]:
df["Active"] = df["Active"].replace({
    "Yes": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    "Y": "Yes",
    1: "Yes",
    "1": "Yes",

    "No": "No",
    "NO": "No",
    "no": "No",
    "N": "No",
    0: "No",
    "0": "No"
})

print(df["Active"].value_counts())

Active
Yes    1371
No      610
Name: count, dtype: int64

#### Q22. Clean Risk_Level
#### Check the distribution of:
#### High
#### Medium
#### Low
#### Verify whether missing values exist.
#### Then display the final class distribution.

In [41]:
print("Risk Level Distribution:")
print(df["Risk_Level"].value_counts())

print("\nMissing values:")
print(df["Risk_Level"].isnull().sum())

print("\nFinal Class Distribution:")
print(df["Risk_Level"].value_counts())

Risk Level Distribution:
Risk_Level
High      1009
Low        548
Medium     483
Name: count, dtype: int64

Missing values:
0

Final Class Distribution:
Risk_Level
High      1009
Low        548
Medium     483
Name: count, dtype: int64

#### Part 6 — Column Transformation
#### Q23. Rename columns
#### Rename these columns:
#### Customer_ID → Customer_ID
#### Annual_Income → AnnualIncome
#### Account_Balance → AccountBalance
#### Credit_Score → CreditScore
#### Tenure_Years → Tenure
#### Join_Date → CustomerJoinDate
#### Risk_Level → RiskLevel
#### Monthly_Spend → MonthlySpend
#### Satisfaction_Score → SatisfactionScore
#### Use rename().

In [43]:
df = df.rename(columns={
    "Customer_ID": "Customer_ID",
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
})
df.columns

Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore',
       'AnnualIncome'],
      dtype='object')

#### Q24. Add a prefix
#### Add:
#### Customer_
#### to every column.
#### Example:
#### Age
#### becomes:
#### Customer_Age
#### Use: add_prefix()

In [51]:
df = df.add_prefix("Customer_")
df.columns

Index(['Customer_Customer_Customer_Customer-Customer_Customer_Customer_Customer_ID',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_Age',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_AnnualIncome',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_AccountBalance',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_CreditScore',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_Tenure',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_City',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_Segment',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_Channel',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_CustomerJoinDate',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_Active',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_RiskLevel',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_MonthlySpend',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_Transactions',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_SatisfactionScore',
       'Customer_Customer_Customer_Customer-Customer_Customer_Customer_AnnualIncome'],
      dtype='object')

#### Q25. Remove unnecessary column
#### Determine whether Customer_ID should be retained for analysis.
#### Create a cleaned DataFrame without the identifier column.
#### Use: drop()

In [56]:
cleaned_df = df.drop(columns=["Customer_ID"])
print(cleaned_df.columns)

KeyError: "['Customer_ID'] not found in axis"