# Pandas + NumPy Data Cleaning

#### 1. Load the CSV using Pandas and display the first 10 rows.

In [4]:
import pandas as pd
df=pd.read_csv("C:\\Users\\ywako\\Downloads\\customer_data - customer_data.csv")

In [5]:
df

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

In [119]:
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

#### 2. Check the number of rows and columns in the dataset.

In [7]:
df.shape

(2000, 15)

#### 3. Display all column names and identify which column names contain leading/trailing spaces or inconsistent capitalization.

In [121]:
for col in df.columns:
    problems = []

    if col != col.strip():
        problems.append("leading/trailing spaces")

    if col != col.lower():
        problems.append("capitalization")

    if problems:
        print(col, "->", ", ".join(problems))

Customer ID -> capitalization
Age -> capitalization
credit Score -> capitalization
City -> capitalization

#### 4. Check the data type of every column using Pandas.

In [122]:
df.dtypes

Customer ID          object
Age                  object
income_usd           object
credit Score         object
tenure_years        float64
monthly_visits      float64
satisfaction        float64
City                 object
customer_segment     object
gender               object
is_active            object
churn_flag           object
signup_date          object
lead_source          object
notes_text           object
dtype: object

#### 5. Calculate the number and percentage of missing values in every column.

In [123]:
df.isna().sum()

Customer ID          20
Age                 331
income_usd          440
credit Score        360
tenure_years        258
monthly_visits      280
satisfaction        399
City                300
customer_segment    380
gender              240
is_active           340
churn_flag          160
signup_date         240
lead_source         420
notes_text          656
dtype: int64

In [124]:
df.isna().mean()*100

Customer ID          1.00
Age                 16.55
income_usd          22.00
credit Score        18.00
tenure_years        12.90
monthly_visits      14.00
satisfaction        19.95
City                15.00
customer_segment    19.00
gender              12.00
is_active           17.00
churn_flag           8.00
signup_date         12.00
lead_source         21.00
notes_text          32.80
dtype: float64

#### 6. Find the rows where Customer ID is missing.

In [125]:
df["Customer ID"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: Customer ID, Length: 2000, dtype: bool

#### 7. Remove leading/trailing whitespace from all column names and convert them  to lowercase with underscores.

In [126]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")

df.columns

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

#### 8. Identify duplicate Customer ID values and count how many duplicates exist.

In [127]:
df['customer_id'].duplicated().sum()

np.int64(19)

#### 9. Remove duplicate customer records while keeping the first occurrence.

In [128]:
df.drop_duplicates()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

#### 10.Find all unique values in the customer_segment column and identify  inconsistent categories such as Consumer, consumer, consumer , etc.

In [131]:
for value in df["customer_segment"].dropna().unique():
    if value != value.strip() or value != value.lower():
        print(repr(value))

'Consumer'
'Enterprise'
'SMB'
'SMB.'
'UNKNOWN'

#### 11.Clean the customer_segment column by standardizing capitalization and  whitespace.

In [133]:
df["customer_segment"] = (
    df["customer_segment"]
    .str.strip()
    .str.title()
)
df["customer_segment"]

0         Consumer
1         Consumer
2         Consumer
3       Enterprise
4       Enterprise
           ...
1995      Consumer
1996           Smb
1997          Smb.
1998           Smb
1999      Consumer
Name: customer_segment, Length: 2000, dtype: object

#### 12.Find all unique values in the gender column and convert them into consistent  categories such as Male and Female.

In [136]:
df["gender"].str.strip().str.lower().str.title()

0        NaN
1       Male
2          M
3          M
4       Male
        ...
1995       M
1996       M
1997       F
1998     NaN
1999     NaN
Name: gender, Length: 2000, dtype: object

#### 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and  No, no, N, 0 become 0.

In [137]:
df["is_active"].astype(str).str.strip().str.lower().replace({
    "yes":1,
    "y":1,
    "l":1,
    "no":0,
    "n":0,
    "0":0
})

0         1
1       nan
2         1
3         0
4         1
       ...
1995      0
1996      0
1997      1
1998      0
1999      1
Name: is_active, Length: 2000, dtype: object

#### 14.Convert the churn_flag column from categorical values (Yes/No) into a binary  numerical column (1/0).

In [139]:
df["churn_flag"].replace({"yes":1,"no":0})

0        No
1        No
2        No
3        No
4        No
       ...
1995     No
1996    Yes
1997     No
1998    Yes
1999     No
Name: churn_flag, Length: 2000, dtype: object

#### 15.Identify all values in income_usd that cannot be directly interpreted as  numbers.

In [141]:
df[pd.to_numeric(df['income_usd'],errors='coerce').isna()]

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,Smb,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
10,CUST-00057,NaN,"$41,941",564.1603365,2.797453,9.0,3.616870,Chennai,Enterprise,M,N,Yes,2021-02-27,NaN,complaint!!!
11,CUST-01293,NaN,NaN,744.4081339,6.966279,1.0,3.990252,Bengaluru,Smb,F,Y,No,09/08/2024,Website,???
13,CUST-00585,NaN,NaN,NaN,2.786554,8.0,NaN,Mumbai,Smb,M,Yes,No,19/08/2022,referral,???
18,CUST-01647,36.56997395,NaN,795.7311323,12.149658,6.0,NaN,Pune,NaN,M,1,No,2025-08-05,website,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1980,CUST-00131,33.32228236,"$58,046",NaN,0.892336,3.0,5.000000,Mumbai,Consumer,Female,Y,Yes,2021-05-13,???,late payment
1985,CUST-00088,38.14992942,NaN,712.2153889,2.553774,8.0,4.180238,Delhi,Consumer,F,0,No,2021-03-30,NaN,NaN
1989,CUST-00467,NaN,NaN,603.905614,3.606269,7.0,3.139857,Bengaluru,Smb,F,Y,No,2022-04-20,Email,NaN
1990,CUST-00122,40.15130762,NaN,762.6314638,4.773822,3.0,4.206313,Bengaluru,Consumer,F,no,No,2021-05-04,???,urgent
1991,CUST-01639,38.09938292,NaN,695.4550712,7.359587,5.0,2.643149,Kolkata,Consumer,Male,0,Yes,2025-07-28,Unknown,NaN

#### 16.Clean income_usd by removing currency symbols, commas, and invalid text,  then convert it to a numeric column using pd.to_numeric().

In [142]:
df['income_usd'].astype(str).str.replace("$",'',regex=False).str.replace(',','',regex=False)

0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 2000, dtype: object

#### 17.Clean the Age column so values such as "35 years" become numeric values.

In [8]:
df["Age"] = df["Age"].astype(str).str.extract(r"(\d+)").astype(float)
df["Age"]

0       45.0
1       47.0
2        NaN
3       62.0
4        NaN
        ...
1995    27.0
1996    41.0
1997    26.0
1998    42.0
1999    59.0
Name: Age, Length: 2000, dtype: float64

#### 18. Identify unrealistic age values using NumPy/Pandas and replace them with NaN.

In [9]:
df[(df["Age"] < 18) | (df["Age"] > 100)]

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
341,CUST-00301,146.0,42001.73818,696.7252495,4.078704,5.0,3.516809,Mumbai,Consumer,M,NaN,No,2021-11-02,email,good customer
467,CUST-00940,120.0,36395.11802,572 pts,1.945215,3.0,3.875453,NaN,Consumer,NaN,0,Yes,2023-08-15,email,NaN
1332,CUST-01543,102.0,50532.4074,501.7796766,5.913152,8.0,3.568511,Delhi,Enterprise,m,NaN,No,2025-04-21,Email,late payment

#### 19.Clean the credit_score column by removing text such as "pts" and converting the column to numeric.

In [26]:
df["credit Score"] = pd.to_numeric(df["credit Score"].astype(str).str.replace("pts", "", regex=False).str.strip(),errors="coerce")
df["credit Score"]

0       660.562918
1       838.000000
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    521.000000
1999    576.739074
Name: credit Score, Length: 2000, dtype: float64