# Pandas Method Question

In [3]:
import pandas as pd

data = {
    "Vehicle_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Brand": ["Toyota", "Honda", "Toyota", "BMW", "Honda", "Audi", "BMW", "Toyota"],
    "Model": ["Camry", "Civic", "Corolla", "X5", "City", "A4", "X3", "Fortuner"],
    "Year": [2020, 2019, 2021, 2022, 2018, 2020, 2021, 2019],
    "Price": [25000, 22000, 18000, 55000, 15000, 40000, 45000, 30000],
    "Mileage": [15, 18, 20, 12, 17, 14, 13, 16],
    "Fuel_Type": ["Petrol", "Petrol", "Diesel", "Diesel", "Petrol", "Petrol", "Diesel", "Diesel"]
}

In [5]:
df = pd.DataFrame(data)

#### Q2. Display the first 5 rows

In [6]:
df.head()

   Vehicle_ID   Brand    Model  Year  Price  Mileage Fuel_Type
0         101  Toyota    Camry  2020  25000       15    Petrol
1         102   Honda    Civic  2019  22000       18    Petrol
2         103  Toyota  Corolla  2021  18000       20    Diesel
3         104     BMW       X5  2022  55000       12    Diesel
4         105   Honda     City  2018  15000       17    Petrol

#### Q3. Display the last 3 rows.

In [7]:
df.tail(3)

   Vehicle_ID   Brand     Model  Year  Price  Mileage Fuel_Type
5         106    Audi        A4  2020  40000       14    Petrol
6         107     BMW        X3  2021  45000       13    Diesel
7         108  Toyota  Fortuner  2019  30000       16    Diesel

#### Q4. Find the number of rows and columns.

In [8]:
df.shape

(8, 7)

#### Q5. Display all column names.

In [9]:
df.columns

Index(['Vehicle_ID', 'Brand', 'Model', 'Year', 'Price', 'Mileage',
       'Fuel_Type'],
      dtype='object')

#### Q6. Display only the Brand column.

In [10]:
df["Brand"]

0    Toyota
1     Honda
2    Toyota
3       BMW
4     Honda
5      Audi
6       BMW
7    Toyota
Name: Brand, dtype: object

#### Q7. Display Brand, Model, and Price.

In [12]:
df[["Brand","Model","Price"]]

    Brand     Model  Price
0  Toyota     Camry  25000
1   Honda     Civic  22000
2  Toyota   Corolla  18000
3     BMW        X5  55000
4   Honda      City  15000
5    Audi        A4  40000
6     BMW        X3  45000
7  Toyota  Fortuner  30000

#### Q8. Display all vehicles whose price is greater than 30000.

In [13]:
df["Price"]>30000

0    False
1    False
2    False
3     True
4    False
5     True
6     True
7    False
Name: Price, dtype: bool

#### Q9. Display vehicles manufactured after 2020.

In [14]:
df["Year"]>2020

0    False
1    False
2     True
3     True
4    False
5    False
6     True
7    False
Name: Year, dtype: bool

#### Q10. Display vehicles where Fuel_Type is "Diesel".

In [15]:
df["Fuel_Type"]=="Diesel"

0    False
1    False
2     True
3     True
4    False
5    False
6     True
7     True
Name: Fuel_Type, dtype: bool

#### Q11. Find the average vehicle price

In [20]:
df.mean

<bound method DataFrame.mean of    Vehicle_ID   Brand     Model  Year  Price  Mileage Fuel_Type
0         101  Toyota     Camry  2020  25000       15    Petrol
1         102   Honda     Civic  2019  22000       18    Petrol
2         103  Toyota   Corolla  2021  18000       20    Diesel
3         104     BMW        X5  2022  55000       12    Diesel
4         105   Honda      City  2018  15000       17    Petrol
5         106    Audi        A4  2020  40000       14    Petrol
6         107     BMW        X3  2021  45000       13    Diesel
7         108  Toyota  Fortuner  2019  30000       16    Diesel>

#### Q12. Find the highest vehicle price.

In [18]:
df.max()

Vehicle_ID       108
Brand         Toyota
Model             X5
Year            2022
Price          55000
Mileage           20
Fuel_Type     Petrol
dtype: object

#### Q13. Find the lowest mileage

In [23]:
df["Mileage"].min()

12

#### 14. Find the average mileage.

In [24]:
df["Mileage"].mean()

np.float64(15.625)

#### Q15. Find how many vehicles belong to each brand.

In [25]:
df["Brand"].value_counts()

Brand
Toyota    3
Honda     2
BMW       2
Audi      1
Name: count, dtype: int64

#### Q16. Check the datatypes.

In [28]:
df.dtypes

Vehicle_ID     int64
Brand         object
Model         object
Year           int64
Price          int64
Mileage        int64
Fuel_Type     object
dtype: object

#### Q17. Check for missing values.

In [29]:
df.isnull().sum()

Vehicle_ID    0
Brand         0
Model         0
Year          0
Price         0
Mileage       0
Fuel_Type     0
dtype: int64

#### Q18. Check for duplicate rows.

In [30]:
df.duplicated().sum()

np.int64(0)

#### Q20.  Find the average price for each `Fuel_Type`

In [37]:
df.groupby("Fuel_Type")["Price"].mean()

Fuel_Type
Diesel    37000.0
Petrol    25500.0
Name: Price, dtype: float64