# Pandas Method

In [3]:
import pandas as pd

df = pd.read_excel("C:\\Users\\ywako\\Downloads\\Bank_customer_churn.xlsx")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### 2. Display the first 8 rows of the dataset.

In [28]:
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

#### 3. Display the last 12 rows of the dataset.

In [29]:
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### 4. Show 10 random rows from the dataset.

In [30]:
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9672,9673,15723013,Sutherland,613,Germany,Male,28,7,76656.40,2,1,1,185483.24,0
1118,1119,15759381,Johnson,617,Spain,Male,61,7,91070.43,1,1,1,101839.77,0
3269,3270,15774744,Lord,664,Germany,Male,33,7,97286.16,2,1,0,143433.33,0
435,436,15581197,Ricci,762,France,Female,51,3,99286.98,1,0,1,85578.63,0
6681,6682,15736717,Ma,602,France,Male,31,7,155271.83,1,1,1,179446.31,0
6889,6890,15651020,Fiorentino,473,France,Female,25,6,110666.42,2,0,0,46758.42,0
4405,4406,15617655,Holt,564,Spain,Female,35,9,0.00,2,1,1,105837.38,0
7909,7910,15570931,Grant,620,France,Male,61,5,0.00,1,0,0,31641.52,1
8246,8247,15608726,Miracle,663,France,Male,24,7,0.00,2,1,1,166310.82,0
4920,4921,15615016,Maurer,515,France,Male,33,2,0.00,2,1,1,136028.97,0

#### 5. Find the shape of the dataset.
#### o How many rows are there?
#### o How many columns are there?

In [33]:
df.shape

(10000, 14)

#### 6. Display complete information about the dataset using one method.
#### o Number of non-null values
#### o Data types
#### o Memory usage

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

#### 7. Print the names of all columns in the dataset.

In [40]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

#### 8. Find the data type of every column.

In [42]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

#### 9. Check for missing values in every column using:
#### o isnull().sum()
#### o isna().sum()

In [51]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

#### 10.Select only one column:
#### o CreditScore

In [50]:
print(df["CreditScore"])

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

####  11.Select the following multiple columns:
####  o CustomerId
####  o Surname
#### o Balance
####  o Exited

In [5]:
df[["CustomerId","Surname","Balance","Exited"]]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

#### 12.Display only numeric columns using select_dtypes().

In [7]:
df.select_dtypes(include=["number"])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

#### 13.Generate the statistical summary of all numeric columns using describe().

In [8]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

#### 14.Check for duplicate rows in the dataset.
#### o How many duplicate rows exist?
#### o Remove all duplicate rows.

In [15]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.drop_duplicates()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### 15.Count the number of customers in each class of the Exited column using value_counts().

In [26]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

# Operators + Loops

#### 1. Take two numbers from user. Perform all arithmetic operations and also check which number is greater using comparison operators.

In [30]:
num1=int(input("Enter first number"))
num2=int(input("Enter second number"))

print("Addition :",num1+num2)
print("Subtraction :",num1-num2)
print("Multiplication :",num1*num2)
print("Division :",num1/num2)
print("Modulus :",num1%num2)
print("Floor Division :",num1//num2)
print("Power :",num1**num2)
print(" ")
if num1>num2:
    print("First number is greater")
elif num2>num1:
    print("Second number is greater")
else:
    print("Both number is equal")

Enter first number 30
Enter second number 15

Addition : 45
Subtraction : 15
Multiplication : 450
Division : 2.0
Modulus : 0
Floor Division : 2
Power : 14348907000000000000000

First number is greater

#### 2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop completely when number 40 is reached using break.

In [31]:
for i in range(1,51):
    if i == 40:
        break
    if i % 5==0:
        continue
    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

#### 3. Take numbers from user until they enter negative number. Calculate sum and average using while loop.

In [36]:
total=0
count=0
while True:
    num=int(input("Enter a number (negative number to stop)"))
    if num < 0:
        break
    total+=num
    count+=1

if count>0:
    average=total/count
    print("Sum =",total)
    print("Average =",average)
else:
    print("No positive number")

Enter a number (negative number to stop) 10
Enter a number (negative number to stop) 20
Enter a number (negative number to stop) 30
Enter a number (negative number to stop) 40
Enter a number (negative number to stop) -4

Sum = 100
Average = 25.0

#### 4. Print the following pattern using nested loops:
#### *****
#### ****
#### ***
#### **
#### *

In [37]:
for i in range(5,0,-1):
    for j in range(i):
        print("*",end="")
    print()

*****
****
***
**
*

#### 5. Find the factorial of a number using for loop and also using while loop.

### Using for loop

In [44]:
num=int(input("Enter a number :"))
factorial=1

if num<0:
    print("Negative number does not exist")

elif num==0:
    print("Factorial of 0 is 1")
else:
    for i in range(1,num+1):
        factorial*=i
    print("Factorial :",factorial)

Enter a number : 8

Factorial : 40320

### Using While loop

In [2]:
num=int(input("Enter a number"))
factorial=1
i=1

while i <= num:
    factorial*=i
    i=i+1

print("Factorial :",factorial)

Enter a number 5

Factorial : 120

# Data Types & Methods

#### 6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace spaces with -, and check if it starts with “Hello”.

In [4]:
text=input("Enter a string :")

print("Uppercase :",text.upper())
print("Count of 'a' :",text.count('a'))
print("Replace space with '-'",text.replace(" ","-"))
print("Start with 'Hello' :",text.startswith("Hello"))

Enter a string : Hello i am yash wakode

Uppercase : HELLO I AM YASH WAKODE
Count of 'a' : 3
Replace space with '-' Hello-i-am-yash-wakode
Start with 'Hello' : True

#### 7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending) and reverse.

In [9]:
numbers=[10,40,20,60,50,30]

print("Original List :",numbers)

numbers.append(70)
print("After append :",numbers)

numbers.insert(2,37)
print("After insert :",numbers)

numbers.remove(30)
print("After remove :",numbers)

numbers.pop()
print("After pop :",numbers)

numbers.sort(reverse=True)
print("After sort :",numbers)

numbers.reverse()
print("After reverse :",numbers)

Original List : [10, 40, 20, 60, 50, 30]
After append : [10, 40, 20, 60, 50, 30, 70]
After insert : [10, 40, 37, 20, 60, 50, 30, 70]
After remove : [10, 40, 37, 20, 60, 50, 70]
After pop : [10, 40, 37, 20, 60, 50]
After sort : [60, 50, 40, 37, 20, 10]
After reverse : [10, 20, 37, 40, 50, 60]

#### 8. Create a dictionary of 4 students (name:marks). Print only those students who scored more than 80 using items().

In [11]:
students={
    "Yash" : 88,
    "Rohit" : 97,
    "Rajat" : 77,
    "Rakesh" : 76,
}

print("Student scored more than 80 marks :")

for name,marks in students.items():
    if marks>80:
        print(name, ":",marks)

Student scored more than 80 marks :
Yash : 88
Rohit : 97

#### 9. Create two sets and perform union, intersection, difference. Also add and discard elements.

In [15]:
set1={10,20,30,40}
set2={30,40,50,60}

print("Set1 :",set1)
print("Set2 :",set2)

print("Union :",set1.union(set2))
print("Intersection :",set1.intersection(set2))
print("Difference :",set1.difference(set2))
set1.add(80)
print("After Add :",set1)
set1.discard(20)
print("After Discard :",set1)

Set1 : {40, 10, 20, 30}
Set2 : {40, 50, 60, 30}
Union : {40, 10, 50, 20, 60, 30}
Intersection : {40, 30}
Difference : {10, 20}
After Add : {40, 10, 80, 20, 30}
After Discard : {40, 10, 80, 30}

# OOP + Encapsulation

#### 10. Create a class Student with private attribute __marks. Add getter and setter with validation (0–100).

In [16]:
class Student:
    def __init__(self, marks):
        self.__marks = 0
        self.set_marks(marks)

    def set_marks(self, marks):
        if 0 <= marks <= 100:
            self.__marks = marks
        else:
            print("Invalid marks! Marks should be between 0 and 100.")

    def get_marks(self):
        return self.__marks

student = Student(76)

print("Marks:", student.get_marks())

student.set_marks(85)
print("Updated Marks:", student.get_marks())

student.set_marks(120)
print("Final Marks:", student.get_marks())

Marks: 76
Updated Marks: 85
Invalid marks! Marks should be between 0 and 100.
Final Marks: 85

#### 11. Create class BankAccount with private __balance. Add deposit and withdraw methods. Raise custom exception if balance becomes negative.

In [17]:
class InsufficientBalanceError(Exception):
    pass

class BankAccount:
    def __init__(self, balance):
        self.__balance = balance

    def deposit(self, amount):
        self.__balance += amount
        print("Deposited:", amount)
        print("Current Balance:", self.__balance)

    def withdraw(self, amount):
        if self.__balance - amount < 0:
            raise InsufficientBalanceError("Insufficient Balance!")
        else:
            self.__balance -= amount
            print("Withdrawn:", amount)
            print("Current Balance:", self.__balance)

    def get_balance(self):
        return self.__balance

account = BankAccount(5000)

try:
    account.deposit(3000)
    account.withdraw(4000)
    account.withdraw(7000)
except InsufficientBalanceError as e:
    print("Error:", e)

print("Final Balance:", account.get_balance())

Deposited: 3000
Current Balance: 8000
Withdrawn: 4000
Current Balance: 4000
Error: Insufficient Balance!
Final Balance: 4000

#### 12. Create class Employee with class attribute company_name. Show that it is shared by all objects. Also update the class attribute.

In [18]:
class Employee:
    company_name = "ABC Technologies"

    def __init__(self, name):
        self.name = name

    def display(self):
        print("Employee Name:", self.name)
        print("Company Name:", Employee.company_name)

emp1 = Employee("Yash")
emp2 = Employee("Rohit")

print("Before Updating Company Name:")
emp1.display()
print()
emp2.display()

Employee.company_name = "RK Solutions"

print("\nAfter Updating Company Name:")
emp1.display()
print()
emp2.display()

Before Updating Company Name:
Employee Name: Yash
Company Name: ABC Technologies

Employee Name: Rohit
Company Name: ABC Technologies

After Updating Company Name:
Employee Name: Yash
Company Name: RK Solutions

Employee Name: Rohit
Company Name: RK Solutions

#### 13. Create class Product with private __price. Add getter and setter. Setter should not allow price less than 100.

In [20]:
class Product:
    def __init__(self, price):
        self.__price = 100
        self.set_price(price)

    def set_price(self, price):
        if price >= 100:
            self.__price = price
        else:
            print("Invalid Price! Price should be at least 100.")

    def get_price(self):
        return self.__price

product = Product(700)

print("Price:", product.get_price())

product.set_price(900)
print("Updated Price:", product.get_price())

product.set_price(50)

print("Final Price:", product.get_price())

Price: 700
Updated Price: 900
Invalid Price! Price should be at least 100.
Final Price: 900

#### 14. Create class Rectangle with private length and width. Add method to calculate area and perimeter.

In [21]:
class Rectangle:
    def __init__(self, length, width):
        self.__length = length
        self.__width = width

    def area(self):
        return self.__length * self.__width

    def perimeter(self):
        return 2 * (self.__length + self.__width)

rect = Rectangle(10, 5)

print("Area:", rect.area())
print("Perimeter:", rect.perimeter())

Area: 50
Perimeter: 30

# Inheritance + Abstraction + super()

#### 15. Create single level inheritance: Person → Student. Use super() in constructor.

In [23]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

class Student(Person):
    def __init__(self, name, age, course):
        super().__init__(name, age)
        self.course = course

    def display(self):
        print("Name:", self.name)
        print("Age:", self.age)
        print("Course:", self.course)

student1 = Student("Yash", 22, "B.Tech CSE")

student1.display()

Name: Yash
Age: 22
Course: B.Tech CSE

#### 16. Create multi-level inheritance: Person → Employee → Manager. Override a method at each level.

In [24]:
class Person:
    def show(self):
        print("I am a Person.")

class Employee(Person):
    def show(self):
        print("I am an Employee.")

class Manager(Employee):
    def show(self):
        print("I am a Manager.")

p = Person()
e = Employee()
m = Manager()

p.show()
e.show()
m.show()

I am a Person.
I am an Employee.
I am a Manager.

#### 17. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound() method.

In [25]:
class Animal:
    def sound(self):
        print("Animal makes a sound.")

class Dog(Animal):
    def sound(self):
        print("Dog says: Bark Bark")

class Cat(Animal):
    def sound(self):
        print("Cat says: Meow Meow")

dog = Dog()
cat = Cat()

dog.sound()
cat.sound()

Dog says: Bark Bark
Cat says: Meow Meow

#### 18. Create abstract class Shape with abstract method area(). Implement it in Circle and Square using super().

In [28]:
from abc import ABC, abstractmethod

class Shape(ABC):
    def __init__(self, value):
        self.value = value

    @abstractmethod
    def area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        super().__init__(radius)

    def area(self):
        return 3.14 * self.value * self.value

class Square(Shape):
    def __init__(self, side):
        super().__init__(side)

    def area(self):
        return self.value * self.value

circle = Circle(8)
square = Square(5)

print("Area of Circle:", circle.area())
print("Area of Square:", square.area())

Area of Circle: 200.96
Area of Square: 25

#### 19. Create multiple inheritance with two classes Father and Mother. Create child class and resolve method conflict.

In [29]:
class Father:
    def show(self):
        print("This is Father's method.")

class Mother:
    def show(self):
        print("This is Mother's method.")

class Child(Father, Mother):
    pass

c = Child()
c.show()

print(Child.__mro__)

This is Father's method.
(<class '__main__.Child'>, <class '__main__.Father'>, <class '__main__.Mother'>, <class 'object'>)

# Overloading + Exception + File Handling

#### 20. Create a class Calculator that can add 2 or 3 numbers (method overloading using *args).

In [30]:
class Calculator:
    def add(self, *args):
        if len(args) == 2:
            print("Sum of 2 numbers:", args[0] + args[1])
        elif len(args) == 3:
            print("Sum of 3 numbers:", args[0] + args[1] + args[2])
        else:
            print("Please enter only 2 or 3 numbers.")

calc = Calculator()

calc.add(10, 20)
calc.add(10, 20, 30)
calc.add(10)

Sum of 2 numbers: 30
Sum of 3 numbers: 60
Please enter only 2 or 3 numbers.

#### 21. Write a program that handles ZeroDivisionError, ValueError and IndexError using multiple except blocks.

In [34]:
try:
    num = int(input("Enter a number: "))

    result = 100 / num
    print("Result:", result)

    numbers = [10, 20, 30]
    index = int(input("Enter index (0-2): "))
    print("Element:", numbers[index])

except ValueError:
    print("Error: Please enter a valid integer.")

except ZeroDivisionError:
    print("Error: Cannot divide by zero.")

except IndexError:
    print("Error: Index is out of range.")

Enter a number:  7

Result: 14.285714285714286

Enter index (0-2):  2

Element: 30

#### 23. Create a custom exception InvalidAgeError. Raise it if age is less than 18.

In [35]:
class InvalidAgeError(Exception):
    pass

try:
    age = int(input("Enter your age: "))

    if age < 18:
        raise InvalidAgeError("Age must be 18 or above.")

    print("You are eligible.")

except InvalidAgeError as e:
    print("Error:", e)

except ValueError:
    print("Error: Please enter a valid number.")

Enter your age:  19

You are eligible.